/*TO DO LIST
* WORK ON LEVEL GENERATION
* WORK ON SPELL SYSTEM
* WORK ON PATHFINDING

* KNOWN BUGS:
* UNIT MOVEMENT WILL READ WRONG TARGET LOCATION OCCASIONALLY
*	DUE TO MIXING UP INDEXES AND QUERY DURING THE READING OF EACH TRANSLATION
* UNITY PHYSICS IS NOT UPDATED WITH UNITY ENTITIES SO WARNING MESSAGES WILL APPEAR
* 	DO NOT CLICK ON ANY ENTITY AS IT WILL GIVE A WARNING THAT IT CANNOT READ THE PHYSICS COMPONENTS
*
*
* ADDITIONAL NOTES:
* NEED TO ADD A REMOVAL COMPONENT AND SYSTEM TO CLEANLY REMOVE ALL ENTITIES WHEN CHANGING SCENE
* ADD THE PAUSED COMPONENT TO ALL ENTITIES AND PREVENT THEM FROM DOING ANYTHING DURING THE PAUSE MENU
*	BOSS PHASE 2 KEEPS SPAWNING PROJECTILES DURING PAUSE, BUT THEY DONT MOVE
*/